pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS =
    }

    stages {
        stage('pull code from git'){
            steps {
                git branch: 'main', url: 'https://github.com/yasirw212/booking-app.git'
            }
        }

        stage('Build'){
            steps {
                sh ('docker build -t yasirwilliams/booking-app:frontend-v1.0.0')
            }
        }

        stage('Login'){
            steps {
                sh ('echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin')
            }
        }

        stage('Push'){
            steps {
                sh ('docker push yasirwilliams/booking-app:frontend-v1.0.0')
            }
        }
    }

    post {
        always {
            sh 'docker logout'
        }
    }
}
